// Automatically generated by syz-sysgen; DO NOT EDIT.

package sys

import (
	"embed"

	"schedtest/sys/generated"

	"schedtest/sys/linux"
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	generated.Register("linux", "amd64", "78e6a92395cad582a96f35c68e3e4d7c87438db9", linux.InitTarget, files)

}
