// Automatically generated by syz-sysgen; DO NOT EDIT.

struct call_attrs_t { 
	uint64_t disabled;
	uint64_t timeout;
	uint64_t prog_timeout;
	uint64_t ignore_return;
	uint64_t breaks_returns;
	uint64_t no_generate;
	uint64_t no_minimize;
	uint64_t remote_cover;
	uint64_t automatic;
	uint64_t automatic_helper;
	uint64_t fsck;
};

struct call_props_t { 
	int fail_nth;
	bool async;
	int rerun;
};

#define read_call_props_t(var, reader) { \
	(var).fail_nth = (int)(reader); \
	(var).async = (bool)(reader); \
	(var).rerun = (int)(reader); \
}


#if GOOS_linux
#define GOOS "linux"

#if GOARCH_amd64
#define GOARCH "amd64"
#define SYZ_REVISION "78e6a92395cad582a96f35c68e3e4d7c87438db9"
#define SYZ_EXECUTOR_USES_FORK_SERVER 1
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4294967296
#define SYZ_DATA_OFFSET 35184372088832
#endif

#endif

