// Automatically generated by syz-sysgen; DO NOT EDIT.
// clang-format off

#if GOOS_linux

#if GOARCH_amd64
const call_t syscalls[] = {
    {"close", 3},
    {"open", 2, {0, 0, 0, 0, 0, 0, 0, 0, 0, 1, }},
    {"syz_builtin0", 0, {1, }},
    {"syz_builtin1", 0, {1, }},
    {"syz_builtin2", 0, {1, }},
    {"syz_builtin3", 0, {1, }},
    {"syz_builtin4", 0, {1, }},
    {"syz_builtin5", 0, {1, }},
};
#endif

#endif

